openapi: 3.1.0
info:
  title: star-api
  description: API Reference for student's knowledge base
  license:
    name: MIT
    url: https://mit-license.org/
  contact: 
    name: Daniil
    url: https://t.me/dadyarri
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
components:
  schemas: {}
tags:
  - name: content
    description: Methodical materials, links, etc 
  - name: persons
    description: Authorization information, useful contacts, etc
  - name: events
    description: Notification system
  - name: tests
    description: Knowledge checking system
